# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04main\"P\n\x0emessagePackage\x12\x16\n\x0emessageContent\x18\x01 \x01(\t\x12\x0e\n\x06\x63lient\x18\x02 \x01(\t\x12\x16\n\x0esequenceNumber\x18\x03 \x01(\t\"#\n\x11sendMessageStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\"3\n\x0bloginStatus\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nclientList\x18\x02 \x01(\t\"-\n\x0cloginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\".\n\rlogoutRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x1e\n\x0clogoutStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\"/\n\x10\x61\x64\x64ServerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"#\n\x11\x61\x64\x64ServerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"5\n\x10getUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.main.loginRequest\"=\n\x13getMessagesResponse\x12&\n\x08messages\x18\x01 \x03(\x0b\x32\x14.main.messagePackage\"%\n\x06Server\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"8\n\x17getKnownServersResponse\x12\x1d\n\x07servers\x18\x01 \x03(\x0b\x32\x0c.main.Server\"\x07\n\x05\x45mpty2\x93\x03\n\x0b\x43hatService\x12.\n\x05login\x12\x12.main.loginRequest\x1a\x11.main.loginStatus\x12\x31\n\x06logout\x12\x13.main.logoutRequest\x1a\x12.main.logoutStatus\x12<\n\x0bsendMessage\x12\x14.main.messagePackage\x1a\x17.main.sendMessageStatus\x12<\n\taddServer\x12\x16.main.addServerRequest\x1a\x17.main.addServerResponse\x12/\n\x08getUsers\x12\x0b.main.Empty\x1a\x16.main.getUsersResponse\x12\x35\n\x0bgetMessages\x12\x0b.main.Empty\x1a\x19.main.getMessagesResponse\x12=\n\x0fgetKnownServers\x12\x0b.main.Empty\x1a\x1d.main.getKnownServersResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEPACKAGE._serialized_start=20
  _MESSAGEPACKAGE._serialized_end=100
  _SENDMESSAGESTATUS._serialized_start=102
  _SENDMESSAGESTATUS._serialized_end=137
  _LOGINSTATUS._serialized_start=139
  _LOGINSTATUS._serialized_end=190
  _LOGINREQUEST._serialized_start=192
  _LOGINREQUEST._serialized_end=237
  _LOGOUTREQUEST._serialized_start=239
  _LOGOUTREQUEST._serialized_end=285
  _LOGOUTSTATUS._serialized_start=287
  _LOGOUTSTATUS._serialized_end=317
  _ADDSERVERREQUEST._serialized_start=319
  _ADDSERVERREQUEST._serialized_end=366
  _ADDSERVERRESPONSE._serialized_start=368
  _ADDSERVERRESPONSE._serialized_end=403
  _GETUSERSRESPONSE._serialized_start=405
  _GETUSERSRESPONSE._serialized_end=458
  _GETMESSAGESRESPONSE._serialized_start=460
  _GETMESSAGESRESPONSE._serialized_end=521
  _SERVER._serialized_start=523
  _SERVER._serialized_end=560
  _GETKNOWNSERVERSRESPONSE._serialized_start=562
  _GETKNOWNSERVERSRESPONSE._serialized_end=618
  _EMPTY._serialized_start=620
  _EMPTY._serialized_end=627
  _CHATSERVICE._serialized_start=630
  _CHATSERVICE._serialized_end=1033
# @@protoc_insertion_point(module_scope)
